builds:
  -
    ldflags:
      - -s -w -X main.PKG_VERSION={{.Version}}
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
      - >-
         {{- if eq .Os "darwin" }}
            GOOS=darwin
            GOARCH={{ .Arch }}
      # - >-
      #   {{- if eq .Os "darwin" }}
      #     {{- if eq .Arch "amd64"}}CC=o64-clang{{- end }}
      #     {{- if eq .Arch "arm64"}}CC=aarch64-apple-darwin20.2-clang{{- end }}
      #   {{- end }}
      #   {{- if eq .Os "windows" }}
      #     {{- if eq .Arch "amd64" }}CC=x86_64-w64-mingw32-gcc{{- end }}
      #   {{- end }}
    binary: semver-gen-{{ .Os }}-{{ .Arch }}
    no_unique_dist_dir: true
    # buildmode: c-shared
    builder: go
    ignore:
      - goos: windows
        goarch: 386
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: amd64